var annotated =
[
    [ "__DIALOG_WINDOW__", "struct____DIALOG__WINDOW____.html", "struct____DIALOG__WINDOW____" ],
    [ "__DT_WORD__", "struct____DT__WORD____.html", "struct____DT__WORD____" ],
    [ "__DT_WORDS__", "struct____DT__WORDS____.html", "struct____DT__WORDS____" ],
    [ "__file_help_buf__", "struct____file__help__buf____.html", "struct____file__help__buf____" ],
    [ "__LISTINFO__", "struct____LISTINFO____.html", "struct____LISTINFO____" ],
    [ "__WB_DIALOG_CONTROL__", "struct____WB__DIALOG__CONTROL____.html", "struct____WB__DIALOG__CONTROL____" ],
    [ "__WB_DIALOG_ENTRY__", "struct____WB__DIALOG__ENTRY____.html", "struct____WB__DIALOG__ENTRY____" ],
    [ "__WB_DIALOG_PROP__", "struct____WB__DIALOG__PROP____.html", "struct____WB__DIALOG__PROP____" ],
    [ "__WB_DIALOG_PROPLIST__", "struct____WB__DIALOG__PROPLIST____.html", "struct____WB__DIALOG__PROPLIST____" ],
    [ "__WB_DIALOG_WINDOW__", "struct____WB__DIALOG__WINDOW____.html", "struct____WB__DIALOG__WINDOW____" ],
    [ "__WB_FRAME_WINDOW__", "struct____WB__FRAME__WINDOW____.html", "struct____WB__FRAME__WINDOW____" ],
    [ "__WB_FW_MENU_HANDLER_", "struct____WB__FW__MENU__HANDLER__.html", "struct____WB__FW__MENU__HANDLER__" ],
    [ "__WBChildFrame__", "struct____WBChildFrame____.html", "struct____WBChildFrame____" ],
    [ "__WBEditWindow__", "struct____WBEditWindow____.html", "struct____WBEditWindow____" ],
    [ "__WBMenu", "struct____WBMenu.html", "struct____WBMenu" ],
    [ "__WBMenuBarWindow__", "struct____WBMenuBarWindow____.html", "struct____WBMenuBarWindow____" ],
    [ "__WBMenuItem__", "struct____WBMenuItem____.html", "struct____WBMenuItem____" ],
    [ "__WBMenuPopupWindow__", "struct____WBMenuPopupWindow____.html", "struct____WBMenuPopupWindow____" ],
    [ "__XSETTINGS_DATA_COLOR__", "struct____XSETTINGS__DATA__COLOR____.html", "struct____XSETTINGS__DATA__COLOR____" ],
    [ "_CHXSetting_", "struct__CHXSetting__.html", "struct__CHXSetting__" ],
    [ "_CHXSettings_", "struct__CHXSettings__.html", "struct__CHXSettings__" ],
    [ "_text_buffer_", "struct__text__buffer__.html", "struct__text__buffer__" ],
    [ "_text_object_", "struct__text__object__.html", "struct__text__object__" ],
    [ "_text_object_vtable_", "struct__text__object__vtable__.html", "struct__text__object__vtable__" ],
    [ "_WB_COMBO_CONTROL_", "struct__WB__COMBO__CONTROL__.html", "struct__WB__COMBO__CONTROL__" ],
    [ "_WB_EDIT_CONTROL_", "struct__WB__EDIT__CONTROL__.html", "struct__WB__EDIT__CONTROL__" ],
    [ "_WB_IMAGE_CONTROL_", "struct__WB__IMAGE__CONTROL__.html", "struct__WB__IMAGE__CONTROL__" ],
    [ "_WB_LIST_CONTROL_", "struct__WB__LIST__CONTROL__.html", "struct__WB__LIST__CONTROL__" ],
    [ "_WB_PUSHBUTTON_CONTROL_", "struct__WB__PUSHBUTTON__CONTROL__.html", "struct__WB__PUSHBUTTON__CONTROL__" ],
    [ "_WB_TREE_CONTROL_", "struct__WB__TREE__CONTROL__.html", "struct__WB__TREE__CONTROL__" ],
    [ "_XPM_ATTRIBUTES_", "struct__XPM__ATTRIBUTES__.html", "struct__XPM__ATTRIBUTES__" ]
];